version: '3'
services:

  #PHP App
  app:
    build:
      context: .
      dockerfile: config/dockerfile
    image: lisa-analysis/php:8.0.8-fpm-alpine3.14_image
    container_name: lisa-analysis_container
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./src/:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - labnet

  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html
      - ./config/conf.d/:/etc/nginx/conf.d/
    networks:
      - labnet

#Docker Networks
networks:
  labnet: 
    name: lisa-analysis_network
